config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products, only: [:show]
    resources :categories, only: [:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/potepan/product_decorator.rb
module Potepan::ProductDecorator
  def related_products(products_count)
    Spree::Product.select("spree_products.*, count(product_id) as count").
                   in_taxons(taxons.ids).
                   where.not(id: id).
                   group("product_id").
                   order("count desc").
                   limit(products_count)
  end

  Spree::Product.prepend self
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxonomies = Spree::Taxonomy.all
    @taxon = Spree::Taxon.find(params[:id])
    @products = @taxon.all_products.includes(master: [:default_price, :images])
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  def show
    @product = Spree::Product.find(params[:id])
    @related_products = @product.related_products(Settings.products_count[:max_count]).
                                 includes(master: [:default_price, :images])
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    if page_title.blank?
      Settings.title[:default]
    else
      "#{page_title} - #{Settings.title[:default]}"
    end
  end
end

app/views/layouts/_cart_contents.html.erb
<ul class="dropdown-menu dropdown-menu-right">
  <li>Item(s) in your cart</li>
  <li>
    <a href="#">
      <div class="media">
        <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
        <div class="media-body">
          <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
        </div>
      </div>
    </a>
  </li>
  <li>
    <a href="#">
      <div class="media">
        <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
        <div class="media-body">
          <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
        </div>
      </div>
    </a>
  </li>
  <li>
    <div class="btn-group" role="group" aria-label="...">
      <button type="button" class="btn btn-default">Shopping Cart</button>
      <button type="button" class="btn btn-default">Checkout</button>
    </div>
  </li>
</ul>

app/views/layouts/_footer.html.erb
<!-- COPY RIGHT -->
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.current.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<!-- Header section -->
<div class="header clearfix">
  <!-- TopBar -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li>
              <span>
                <a data-toggle="modal" href="#login">Login</a><small>or</small>
                <a data-toggle="modal" href="#signup">Sign up</a>
              </span>
            </li>
            <li class="dropdown searchBox">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <span class="input-group">
                    <input type="text" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                    <span class="input-group-addon" id="basic-addon2">Search</span>
                  </span>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-shopping-cart"></i></a>
              <% if current_page?(controller: "sample", action: "cart_page") %>
                <%= render 'layouts/default_cart' %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("img/logo.png", :alt => ""), potepan_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", potepan_path %></li>
          <li class="dropdown megaDropMenu active">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
            <% if %w[about_us privacy_policy blog_left_sidebar blog_right_sidebar blog_single_left_sidebar blog_single_right_sidebar product_list_left_sidebar tokushoho product_grid_left_sidebar cart_page].any? { |name| current_page?(send("potepan_#{name}_path")) } %>
              <%= render "layouts/navbar_product" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/_header_page.html.erb
<% unless %w[potepan potepan_index].any? { |name| current_page?(send("#{name}_path")) } %>
  <!-- Light section -->
  <section class="lightSection clearfix pageHeader">
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <div class="page-title">
            <h2><%= yield(:title) %></h2>
          </div>
        </div>
        <div class="col-xs-6">
          <ol class="breadcrumb pull-right">
            <li><%= breadcrumbs separator: "&emsp;/&emsp;" %></li>
          </ol>
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/layouts/_modal.html.erb
<!-- LOGIN MODAL -->
<div class="modal fade" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="#" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">Enter Email</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">Password</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block" disabled>log in</button>
          <button type="button" class="btn btn-link btn-block" disabled>Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- SIGN UP MODAL -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Create an account</h3>
      </div>
      <div class="modal-body">
        <form action="#" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">Enter Email</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">Password</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">Confirm Password</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block" disabled>Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar_product.html.erb
<ul class="dropdown-menu row">
  <li class="col-sm-3 col-xs-12">
    <ul class="list-unstyled">
      <li>Products Grid View</li>
      <li><a href="product_grid_left_sidebar.html">Products Sidebar Left</a></li>
      <li><a href="product-grid-right-sidebar.html">Products Sidebar Right</a></li>
      <li><a href="product-grid-3-col-filter.html">Products 3 Columns V1</a></li>
      <li><a href="product-grid-3-col.html">Products 3 Columns V2</a></li>
      <li><a href="product-grid-4-col.html">Products 4 Columns</a></li>
    </ul>
  </li>
  <li class="col-sm-3 col-xs-12">
    <ul class="list-unstyled">
      <li>Products List View</li>
      <li><a href="product_list_left_sidebar.html">Products Sidebar Left</a></li>
      <li><a href="product-list-right-sidebar.html">Products Sidebar Right</a></li>
      <li class="listHeading">Others</li>
      <li><a href="single-product.html">Single Product</a></li>
      <li class="active"><a href="cart_page.html">Cart Page</a></li>
    </ul>
  </li>
  <li class="col-sm-3 col-xs-12">
    <ul class="list-unstyled">
      <li>Checkout</li>
      <li><a href="checkout_step_1.html">Step 1 - Address</a></li>
      <li><a href="checkout_step_2.html">Step 2 - Shipping</a></li>
      <li><a href="checkout_step_3.html">Step 3 - Payment</a></li>
      <li><a href="checkout_step_4.html">Step 4 - Payment</a></li>
      <li><a href="checkout_complete.html">Order Complete</a></li>
    </ul>
  </li>
  <li class="col-sm-3 col-xs-12">
    <a href="#" class="menu-photo"><%= image_tag("img/menu-photo.jpg", :alt => "menu-img") %></a>
  </li>
</ul>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all' %>
<!-- GOOGLE FONT -->
<%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', media: 'all' %>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div class="main-wrapper">
      <%= render 'layouts/header' %>
      <%= render 'layouts/header_page' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= render 'layouts/modal' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/show.html.erb
<% provide(:title, @taxon.name) %>
<% breadcrumb :taxon_title, @taxon %>
<!-- Main Content Section -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <div class="panel panel-default">
          <div class="panel-heading">商品カテゴリー</div>
          <div class="panel-body">
            <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
              <ul class="nav navbar-nav side-nav">
                <% @taxonomies.each do |taxonomy| %>
                  <li>
                    <a href="#" data-toggle="collapse" data-target="#<%= "taxonomy_#{taxonomy.id}" %>"><%= taxonomy.name %><i class="fa fa-plus"></i></a>
                    <ul id="<%= "taxonomy_#{taxonomy.id}" %>" class="collapse collapseItem">
                      <% taxonomy.root.leaves.each do |taxon| %>
                        <li>
                          <%= link_to potepan_category_path(taxon.id) do %>
                            <i class="fa fa-caret-right" aria-hidden="true"></i><%= taxon.name %> <span>(<%= taxon.products.count %>)</span>
                          <% end %>
                        </li>
                      <% end %>
                    </ul>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
        <div class="panel panel-default filterNormal">
          <div class="panel-heading">色から探す</div>
          <div class="panel-body">
            <ul class="list-unstyled">
              <li><a href="#">ブラック<span>(15)</span></a></li>
              <li><a href="#">ホワイト<span>(10)</span></a></li>
              <li><a href="#">レッド<span>(7)</span></a></li>
              <li><a href="#">ブルー<span>(12)</span></a></li>
              <li><a href="#">オレンジ<span>(12)</span></a></li>
            </ul>
          </div>
        </div>
        <div class="panel panel-default filterNormal">
          <div class="panel-heading">サイズから探す</div>
          <div class="panel-body">
            <ul class="list-unstyled clearfix">
              <li><a href="#">S<span>(15)</span></a></li>
              <li><a href="#">M<span>(10)</span></a></li>
              <li><a href="#">L<span>(7)</span></a></li>
              <li><a href="#">XL<span>(12)</span></a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <div class="col-xs-6">
            <select name="guiest_id1" id="guiest_id1" class="select-drop">
              <option value="0">並び替え</option>
              <option value="1">人気順</option>
              <option value="2">安い順</option>
              <option value="3">新着順</option>
              <option value="3">高い順</option>
            </select>
          </div>
          <div class="col-xs-6">
            <div class="btn-group pull-right" role="group">
              <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
              <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
            </div>
          </div>
        </div>
        <div class="row">
          <% @products.each do |product| %>
            <div class="col-sm-4 col-xs-12">
              <div class="productBox product_<%= "#{product.id}" %>">
                <%= link_to potepan_product_path(product.id) do %>
                  <div class="productImage clearfix">
                    <% if product.images.blank? %>
                      <%= image_tag("img/products/products-01.jpg", :alt => "products-img") %>
                    <% else %>
                      <%= image_tag(product.images.first.attachment(:product), alt: "products-img") %>
                    <% end %>
                  </div>
                  <div class="productCaption clearfix">
                    <h5><%= product.name %></h5>
                    <h3><%= product.display_price %></h3>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Light Section -->
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <% logo_slide_num = [*1..5] %>
          <% logo_slide_num.each do |i| %>
            <div class="slide">
              <div class="partnersLogo clearfix">
                <%= image_tag("img/home/partners/partner-0#{i}.png", alt: "partner-img") %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name) %>
<% breadcrumb :product_title, @product %>
<!-- Main content section -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <% if @product.images.present? %>
                  <% @product.images.each do |image| %>
                    <div class="item <%= "active" if image.position == 1 %>" data-thumb="<%= image.position - 1 %>">
                      <%= image_tag(image.attachment(:product), itemprop: "image") %>
                    </div>
                  <% end %>
                <% else %>
                  <div class="item active" data-thumb="0">
                    <%= image_tag("img/products/signle-product/product-slide-big-01.jpg") %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="clearfix">
              <div id="thumbcarousel" class="carousel slide" data-interval="false">
                <div class="carousel-inner">
                  <% if @product.images.present? %>
                    <% @product.images.each do |image| %>
                      <div data-target="#carousel" data-slide-to="<%= image.position - 1 %>" class="thumb">
                        <%= image_tag(image.attachment(:product), itemprop: "image") %>
                      </div>
                    <% end %>
                  <% else %>
                    <div data-target="#carousel" data-slide-to="0" class="thumb">
                      <%= image_tag("img/products/signle-product/product-slide-small-01.jpg") %>
                    </div>
                  <% end %>
                </div>
                <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div>
            </div>
          </div>
          <div class="media-body">
            <ul class="list-inline">
              <li>
                <%= link_to potepan_category_path(@product.taxons.first.id) do %>
                  <i class="fa fa-reply" area-hidden="true"></i>一覧ページへ戻る
                <% end %>
              </li>
            </ul>
            <h2><%= @product.name %></h2>
            <h3><%= @product.display_price %></h3>
            <p><%= @product.description %></p>
            <span class="quick-drop">
              <section name="guidest_id3" id="guidest_id3" class="select-drop">
                <option value="0">S</option>
                <option value="1">M</option>
                <option value="2">L</option>
                <option value="3">XL</option>
              </section>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row productsContent">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>関連商品</h4>
        </div>
      </div>
      <% @related_products.each do |related_product| %>
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="productBox">
            <%= link_to potepan_product_path(related_product.id) do %>
              <div class="productImage clearfix">
                <% if related_product.images.present? %>
                  <%= image_tag(related_product.images.first.attachment(:product), alt: "products-img") %>
                <% else %>
                  <%= image_tag("img/products/products-01.jpg", :alt => "products-img") %>
                <% end %>
              </div>
              <div class="productCaption clearfix">
                <h5><%= related_product.name %></h5>
                <h3><%= related_product.display_price %></h3>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/potepan/sample/cart_page.html.erb
<% provide(:title, "Cart") %>
<% breadcrumb :default_title, yield(:title) %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix cartListWrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="cartListInner">
          <form action="#">
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th></th>
                    <th>商品名</th>
                    <th>価格</th>
                    <th>数</th>
                    <th>小計</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td class="col-xs-2">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <span class="cartImage"><%= image_tag("img/products/cart-image.jpg", :alt => "image") %></span>
                    </td>
                    <td class="col-xs-4">Italian Winter Hat</td>
                    <td class="col-xs-2">99円</td>
                    <td class="col-xs-2"><input type="text" placeholder="1"></td>
                    <td class="col-xs-2">99円</td>
                  </tr>
                  <tr>
                    <td class="col-xs-2">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <span class="cartImage"><%= image_tag("img/products/cart-image.jpg", :alt => "image") %></span>
                    </td>
                    <td class="col-xs-4">Italian Winter Hat</td>
                    <td class="col-xs-2">99円</td>
                    <td class="col-xs-2"><input type="text" placeholder="1"></td>
                    <td class="col-xs-2">99円</td>
                  </tr>
                  <tr>
                    <td class="col-xs-2">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <span class="cartImage"><%= image_tag("img/products/cart-image.jpg", :alt => "image") %></span>
                    </td>
                    <td class="col-xs-4">Italian Winter Hat</td>
                    <td class="col-xs-2">99円</td>
                    <td class="col-xs-2"><input type="text" placeholder="1"></td>
                    <td class="col-xs-2">99円</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div class="updateArea">
              <a href="#" class="btn">アップデート</a>
            </div>
            <div class="totalAmountArea">
              <div class="col-sm-4 col-sm-offset-8 col-xs-12">
                <ul class="list-unstyled">
                  <li>小計 <span>792円</span></li>
                  <li>消費税 <span>18円</span></li>
                  <li>総計 <span class="grandTotal">810円</span></li>
                </ul>
              </div>
            </div>
            <div class="checkBtnArea">
              <a href="checkout_step_1.html" class="btn btn-primary btn-block">購入する<i class="fa fa-arrow-circle-right" aria-hidden="true"></i></a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/sample/checkout_complete.html.erb
<% provide(:title, "Order Completed") %>
<% breadcrumb :default_title, yield(:title) %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix setp5">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="thanksContent">
          <h2>Thank You !! <small>ご注文ありがとうございます。</small></h2>
          <h3>Shipping Details</h3>
          <div class="thanksInner">
            <div class="row">
              <div class="col-sm-6 col-xs-12 tableBlcok">
                <address>
                  <span>Shipping address:</span> <a href="mailto:potepan@potepancamp.com">potepan@potepancamp.com</a> <br>
                  <span>Email:</span> <a href="mailto:potepan@potepancamp.com">potepan@potepancamp.com</a> <br>
                  <span>Phone:</span> +884 5452 6432
                </address>
              </div>
              <div class="col-sm-6 col-xs-12">
                <div class="well">
                  <h2><small>Order ID</small>9547</h2>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>